
rem NOTE: this batch file is to be run in a Visual Studio command prompt

rem Delete old files
del *.obj
del *.ilk
del *.exe

rem Delete, compile and link files into .obj files in current directory
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE469_Use_Of_Pointer_Subtraction_To_Determine_Size\*.c" "testcases\CWE469_Use_Of_Pointer_Subtraction_To_Determine_Size\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE511_Logic_Time_Bomb\*.c" "testcases\CWE511_Logic_Time_Bomb\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE188_Reliance_On_Data_Memory_Layout\*.c" "testcases\CWE188_Reliance_On_Data_Memory_Layout\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE256_Plaintext_Storage_of_Password\*.c" "testcases\CWE256_Plaintext_Storage_of_Password\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE366_Race_Condition_Within_A_Thread\*.c" "testcases\CWE366_Race_Condition_Within_A_Thread\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE197_Numeric_Truncation_Error\*.c" "testcases\CWE197_Numeric_Truncation_Error\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE327_Use_Broken_Crypto\*.c" "testcases\CWE327_Use_Broken_Crypto\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE591_Sensitive_Data_Storage_in_Improperly_Locked_Memory\*.c" "testcases\CWE591_Sensitive_Data_Storage_in_Improperly_Locked_Memory\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE390_Error_Without_Action\*.c" "testcases\CWE390_Error_Without_Action\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE605_Multiple_Binds_Same_Port\*.c" "testcases\CWE605_Multiple_Binds_Same_Port\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE374_Passing_Mutable_Objects_to_Untrusted_Method\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE259_Hard_Coded_Password\*.c" "testcases\CWE259_Hard_Coded_Password\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE482_Comparing_instead_of_Assigning\*.c" "testcases\CWE482_Comparing_instead_of_Assigning\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE15_External_Control_of_System_or_Configuration_Setting\*.c" "testcases\CWE15_External_Control_of_System_or_Configuration_Setting\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE785_Path_Manipulation_Function_Without_Max_Sized_Buffer\*.c" "testcases\CWE785_Path_Manipulation_Function_Without_Max_Sized_Buffer\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE675_Duplicate_Operations_on_Resource\*.c" "testcases\CWE675_Duplicate_Operations_on_Resource\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE762_Mismatched_Memory_Management_Routines\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE480_Use_of_Incorrect_Operator\*.c" "testcases\CWE480_Use_of_Incorrect_Operator\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE321_Hard_Coded_Cryptographic_Key\*.c" "testcases\CWE321_Hard_Coded_Cryptographic_Key\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE124_Buffer_Underwrite\*.c" "testcases\CWE124_Buffer_Underwrite\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE187_Partial_Comparison\*.c" "testcases\CWE187_Partial_Comparison\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE476_NULL_Pointer_Dereference\*.c" "testcases\CWE476_NULL_Pointer_Dereference\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE535_Info_Leak_Shell_Error\*.c" "testcases\CWE535_Info_Leak_Shell_Error\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE242_Use_of_Inherently_Dangerous_Function\*.c" "testcases\CWE242_Use_of_Inherently_Dangerous_Function\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE223_Omission_Of_Security_Relevant_Information\*.c" "testcases\CWE223_Omission_Of_Security_Relevant_Information\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE666_Operation_on_Resource_in_Wrong_Phase_of_Lifetime\*.c" "testcases\CWE666_Operation_on_Resource_in_Wrong_Phase_of_Lifetime\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE284_Access_Control_Issues\*.c" "testcases\CWE284_Access_Control_Issues\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE563_Unused_Variable\*.c" "testcases\CWE563_Unused_Variable\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE400_Resource_Exhaustion\*.c" "testcases\CWE400_Resource_Exhaustion\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE672_Operation_on_Resource_After_Expiration_or_Release\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE127_Buffer_Underread\*.c" "testcases\CWE127_Buffer_Underread\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE547_Hardcoded_Security_Constants\*.c" "testcases\CWE547_Hardcoded_Security_Constants\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE534_Info_Leak_Debug_Log\*.c" "testcases\CWE534_Info_Leak_Debug_Log\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE467_Use_of_sizeof_on_Pointer_Type\*.c" "testcases\CWE467_Use_of_sizeof_on_Pointer_Type\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE364_Signal_Handler_Race_Condition\*.c" "testcases\CWE364_Signal_Handler_Race_Condition\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE475_Undefined_Behavior_For_Input_to_API\*.c" "testcases\CWE475_Undefined_Behavior_For_Input_to_API\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE489_Leftover_Debug_Code\*.c" "testcases\CWE489_Leftover_Debug_Code\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE426_Untrusted_Search_Path\*.c" "testcases\CWE426_Untrusted_Search_Path\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE78_OS_Command_Injection\*.c" "testcases\CWE78_OS_Command_Injection\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE122_Heap_Based_Buffer_Overflow\*.c" "testcases\CWE122_Heap_Based_Buffer_Overflow\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE247_Reliance_On_DNS_Lookups_In_A_Security_Decision\*.c" "testcases\CWE247_Reliance_On_DNS_Lookups_In_A_Security_Decision\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE114_Process_Control\*.c" "testcases\CWE114_Process_Control\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE761_Free_Pointer_Not_At_Start_Of_Buffer\*.c" "testcases\CWE761_Free_Pointer_Not_At_Start_Of_Buffer\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE772_Missing_Release_of_Resource_after_Effective_Lifetime\*.c" "testcases\CWE772_Missing_Release_of_Resource_after_Effective_Lifetime\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE222_Truncation_Of_Security_Relevant_Information\*.c" "testcases\CWE222_Truncation_Of_Security_Relevant_Information\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE131_Incorrect_Calculation_Of_Buffer_Size\*.c" "testcases\CWE131_Incorrect_Calculation_Of_Buffer_Size\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcasesupport\*.c" "testcasesupport\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE248_Uncaught_Exception\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE253_Incorrect_Check_of_Function_Return_Value\*.c" "testcases\CWE253_Incorrect_Check_of_Function_Return_Value\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE674_Uncontrolled_Recursion\*.c" "testcases\CWE674_Uncontrolled_Recursion\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE195_Signed_To_Unsigned_Conversion\*.c" "testcases\CWE195_Signed_To_Unsigned_Conversion\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE396_Catch_Generic_Exception\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE377_Insecure_Temporary_File\*.c" "testcases\CWE377_Insecure_Temporary_File\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE571_Expression_Always_True\*.c" "testcases\CWE571_Expression_Always_True\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE685_Function_Call_With_Incorrect_Number_Of_Arguments\*.c" "testcases\CWE685_Function_Call_With_Incorrect_Number_Of_Arguments\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE328_Reversible_Oneway_Hash\*.c" "testcases\CWE328_Reversible_Oneway_Hash\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE226_Sensitive_Information_Uncleared_Before_Release\*.c" "testcases\CWE226_Sensitive_Information_Uncleared_Before_Release\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE401_Memory_Leak\*.c" "testcases\CWE401_Memory_Leak\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE590_Free_Of_Invalid_Pointer_Not_On_The_Heap\*.c" "testcases\CWE590_Free_Of_Invalid_Pointer_Not_On_The_Heap\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE484_Omitted_Break_Statement\*.c" "testcases\CWE484_Omitted_Break_Statement\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE123_Write_What_Where_Condition\*.c" "testcases\CWE123_Write_What_Where_Condition\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE365_Race_Condition_In_Switch\*.c" "testcases\CWE365_Race_Condition_In_Switch\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE561_Dead_Code\*.c" "testcases\CWE561_Dead_Code\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE690_NULL_Deref_from_Return\*.c" "testcases\CWE690_NULL_Deref_from_Return\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE570_Expression_Always_False\*.c" "testcases\CWE570_Expression_Always_False\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE36_Absolute_Path_Traversal\*.c" "testcases\CWE36_Absolute_Path_Traversal\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE680_Integer_Overflow_To_Buffer_Overflow\*.c" "testcases\CWE680_Integer_Overflow_To_Buffer_Overflow\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE440_Expected_Behavior_Violation\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE135_Incorrect_Calculation_Of_Multibyte_String_Length\*.c" "testcases\CWE135_Incorrect_Calculation_Of_Multibyte_String_Length\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE415_Double_Free\*.c" "testcases\CWE415_Double_Free\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE427_Uncontrolled_Search_Path_Element\*.c" "testcases\CWE427_Uncontrolled_Search_Path_Element\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE676_Use_of_Potentially_Dangerous_Function\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE196_Unsigned_To_Signed_Conversion_Error\*.c" "testcases\CWE196_Unsigned_To_Signed_Conversion_Error\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE560_Use_Of_umask_With_chmod_Style_Argument\*.c" "testcases\CWE560_Use_Of_umask_With_chmod_Style_Argument\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE620_Unverified_Password_Change\*.c" "testcases\CWE620_Unverified_Password_Change\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE468_Incorrect_Pointer_Scaling\*.c" "testcases\CWE468_Incorrect_Pointer_Scaling\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE191_Integer_Underflow\*.c" "testcases\CWE191_Integer_Underflow\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE391_Unchecked_Error_Condition\*.c" "testcases\CWE391_Unchecked_Error_Condition\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE478_Failure_To_Use_Default_Case_In_Switch\*.c" "testcases\CWE478_Failure_To_Use_Default_Case_In_Switch\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE126_Buffer_Overread\*.c" "testcases\CWE126_Buffer_Overread\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE758_Undefined_Behavior\*.c" "testcases\CWE758_Undefined_Behavior\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE190_Integer_Overflow\*.c" "testcases\CWE190_Integer_Overflow\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE481_Assigning_instead_of_Comparing\*.c" "testcases\CWE481_Assigning_instead_of_Comparing\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE789_Uncontrolled_Mem_Alloc\*.c" "testcases\CWE789_Uncontrolled_Mem_Alloc\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE193_Off_by_One_Error\*.c" "testcases\CWE193_Off_by_One_Error\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE392_Failure_To_Report_Error_In_Status_Code\*.c" "testcases\CWE392_Failure_To_Report_Error_In_Status_Code\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE416_Use_After_Free\*.c" "testcases\CWE416_Use_After_Free\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE129_Improper_Validation_Of_Array_Index\*.c" "testcases\CWE129_Improper_Validation_Of_Array_Index\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE369_Divide_By_Zero\*.c" "testcases\CWE369_Divide_By_Zero\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE464_Insertion_Of_Data_Structure_Sentinel\*.c" "testcases\CWE464_Insertion_Of_Data_Structure_Sentinel\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE272_Least_Privilege_Principal\*.c" "testcases\CWE272_Least_Privilege_Principal\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE457_Use_of_Uninitialized_Variable\*.c" "testcases\CWE457_Use_of_Uninitialized_Variable\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE546_Suspicious_Comment\*.c" "testcases\CWE546_Suspicious_Comment\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE404_Improper_Resource_Shutdown\*.c" "testcases\CWE404_Improper_Resource_Shutdown\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE338_Weak_PRNG\*.c" "testcases\CWE338_Weak_PRNG\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE252_Unchecked_Return_Value\*.c" "testcases\CWE252_Unchecked_Return_Value\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE204_Response_Discrepancy_Information_Leak\*.c" "testcases\CWE204_Response_Discrepancy_Information_Leak\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE562_Return_Of_Stack_Variable_Address\*.c" "testcases\CWE562_Return_Of_Stack_Variable_Address\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer\*.c" "testcases\CWE588_Attempt_To_Access_Child_Of_A_Non_Structure_Pointer\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE170_Improper_Null_Termination\*.c" "testcases\CWE170_Improper_Null_Termination\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE665_Improper_Initialization\*.c" "testcases\CWE665_Improper_Initialization\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE688_Function_Call_With_Incorrect_Variable_Or_Reference_As_Argument\*.c" "testcases\CWE688_Function_Call_With_Incorrect_Variable_Or_Reference_As_Argument\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE134_Uncontrolled_Format_String\*.c" "testcases\CWE134_Uncontrolled_Format_String\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE367_TOC_TOU\*.c" "testcases\CWE367_TOC_TOU\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE244_Failure_to_Clear_Heap_Before_Release\*.c" "testcases\CWE244_Failure_to_Clear_Heap_Before_Release\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE606_Unchecked_Loop_Condition\*.c" "testcases\CWE606_Unchecked_Loop_Condition\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE23_Relative_Path_Traversal\*.c" "testcases\CWE23_Relative_Path_Traversal\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE587_Assignment_Of_Fixed_Address_To_Pointer\*.c" "testcases\CWE587_Assignment_Of_Fixed_Address_To_Pointer\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE483_Incorrect_Block_Delimitation\*.c" "testcases\CWE483_Incorrect_Block_Delimitation\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE479_Unsafe_Call_from_a_Signal_Handler\*.c" "testcases\CWE479_Unsafe_Call_from_a_Signal_Handler\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE194_Unexpected_Sign_Extension\*.c" "testcases\CWE194_Unexpected_Sign_Extension\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE459_Incomplete_Cleanup\*.c" "testcases\CWE459_Incomplete_Cleanup\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE273_Improper_Check_for_Dropped_Privileges\*.c" "testcases\CWE273_Improper_Check_for_Dropped_Privileges\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE121_Stack_Based_Buffer_Overflow\*.c" "testcases\CWE121_Stack_Based_Buffer_Overflow\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE397_Throw_Generic_Exception\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE319_Plaintext_Tx_Sensitive_Info\*.c" "testcases\CWE319_Plaintext_Tx_Sensitive_Info\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo /c "testcases\CWE617_Reachable_Assertion\*.c" "testcases\CWE617_Reachable_Assertion\*.cpp" testcasesupport\io.c testcasesupport\std_thread.c
cl /FeTestcases *.obj /I"testcasesupport" /W3 /MT /GS /RTC1 /bigobj /EHsc /nologo
